"""Regenerate the Sites Drizzle definition from the canonical, trusted SQL schema."""
import re
import sqlite3
from pathlib import Path

root = Path(__file__).parent
db = sqlite3.connect(':memory:')
db.executescript((root / 'd1-schema.sql').read_text())
lines = [
    '// Generated by ../sync_schema.py from ../d1-schema.sql. Edit the canonical SQL.',
    "import { sqliteTable, integer, real, text, check, index } from 'drizzle-orm/sqlite-core';",
    "import { sql } from 'drizzle-orm';",
]
for name, ddl in db.execute("SELECT name, sql FROM sqlite_master WHERE type='table' AND name != 'sqlite_sequence' ORDER BY rowid"):
    foreign = {row[3]: (row[2], row[4]) for row in db.execute(f'PRAGMA foreign_key_list({name})')}
    unique = set()
    indexes = []
    for row in db.execute(f'PRAGMA index_list({name})'):
        cols = [r[2] for r in db.execute(f'PRAGMA index_info({row[1]})')]
        if row[2] and len(cols) == 1:
            unique.add(cols[0])
        elif row[3] == 'c':
            indexes.append((row[1], cols))
    lines.append(f"export const {name} = sqliteTable('{name}', {{")
    for _, col, kind, required, default, primary in db.execute(f'PRAGMA table_info({name})'):
        builder = {'INTEGER': 'integer', 'REAL': 'real', 'TEXT': 'text'}[kind]
        expr = f"{builder}('{col}')"
        if primary:
            expr += '.primaryKey({ autoIncrement: true })' if kind == 'INTEGER' else '.primaryKey().notNull()'
        elif required:
            expr += '.notNull()'
        if col in unique:
            expr += '.unique()'
        if default is not None:
            expr += f'.default(sql.raw({default!r}))'
        if col in foreign:
            table, target = foreign[col]
            expr += f'.references(() => {table}.{target})'
        lines.append(f'  {col}: {expr},')
    constraints = []
    for n, match in enumerate(re.finditer(r'\bCHECK\s*\(', ddl), 1):
        start = match.end()
        depth, end = 1, start
        while depth:
            depth += (ddl[end] == '(') - (ddl[end] == ')')
            end += 1
        expression = ddl[start:end-1]
        # Canonical SQL has no quoted parenthesis characters in its CHECK expressions.
        constraints.append(f"  check('{name}_check_{n}', sql.raw({expression!r})),")
    constraints += [f"  index('{idx}').on({', '.join('t.'+c for c in cols)})," for idx, cols in indexes]
    lines.append('}, (t) => [')
    lines.extend(constraints)
    lines.append(']);')
target = root / 'site/db/schema.ts'
target.write_text('\n'.join(lines)+'\n')
print('Generated site/db/schema.ts from d1-schema.sql')
