import { adviserConfigured } from '../adviser';
import { countrySnapshotNote } from '../../lib/source-status.mjs';
import { notFound } from 'next/navigation';
import { InvestmentPanel } from '../investment-panel';
import { EvidenceFilter, ManagementForms } from '../project-tools';
import { investmentInputs } from '../data';
import { canManage } from '../../lib/management.mjs';
import dossier from '../../db/dossier.json';
import { snapshot } from '../data';
import { registeredAccount } from '../auth';
import { getChatGPTUser, chatGPTSignInPath, chatGPTSignOutPath } from '../chatgpt-auth';
import { Refresh, AdviserForm, RegistrationForm } from '../widgets';
export const dynamic='force-dynamic';
const titles:Record<string,string>={'investment':'Investment model','decision':'Decision dossier','manage':'Manage evidence','country-comparison':'Country Comparison','initial-design':'Initial Design','evidence':'Evidence','ask-the-adviser':'Ask the Adviser'};
function Badge({kind}:{kind:string}){return <span className={`badge ${kind}`}>{kind.replaceAll('_',' ')}</span>;}
function MetricTable({metrics}:{metrics:any[]}){return <div className="table-wrap"><table><thead><tr><th>Country / scope</th><th>Metric</th><th>Value / type</th><th>Reporting period</th><th>Source / retrieved</th></tr></thead><tbody>{metrics.map(m=><tr key={m.id}><td><strong>{m.country_name}</strong><small>{m.geographic_scope}</small></td><td>{m.metric_name.replaceAll('_',' ')}{m.category&&<small>{m.category}</small>}</td><td><strong>{m.value===null?'Unknown':Number(m.value).toLocaleString('en-US',{maximumFractionDigits:4})} {m.unit}</strong><small>{m.value_kind} · {m.confidence} confidence</small></td><td>{m.reporting_period||'Unknown'}<small>{m.notes}</small></td><td><a href={m.source_url} target="_blank" rel="noreferrer">[S{m.source_id}] {m.source_title}</a><small>{m.retrieved_at}</small></td></tr>)}</tbody></table></div>;}
export default async function Section({params}:{params:Promise<{section:string}>}){
  const {section}=await params;
  if(['register','login','account'].includes(section)){
    const user=await getChatGPTUser();
    let account;try{account=user?await registeredAccount(user.userId):null;}catch{return <div className="notice">Account storage is temporarily unavailable. Please try again.</div>;}
    return <div className="account-page"><div className="page-heading"><div><p className="eyebrow">Global Datacenter Design Explorer</p><h1>{account?'Your account':'Sign in and register'}</h1><p>Use ChatGPT to verify your identity, then complete website registration.</p></div></div><section className="panel">{!user?<><h2>1. Sign in with ChatGPT</h2><p>Continue through ChatGPT, then return here to register for this website.</p><a className="button" href={chatGPTSignInPath('/register')} target="_top">Sign in with ChatGPT</a></>:account?<><h2>{user.displayName}</h2><dl><dt>Email</dt><dd>{user.email}</dd><dt>Account ID</dt><dd>{account.id}</dd><dt>Access</dt><dd>{account.role}</dd><dt>Registered</dt><dd>{account.registered_at}</dd></dl><div className="account-actions"><a className="button" href="/ask-the-adviser">Open the Adviser</a><a className="button secondary" href={chatGPTSignOutPath()} target="_top">Sign out</a></div></>:<><h2>2. Complete website registration</h2><p>Signed in as {user.displayName} ({user.email}). Your ChatGPT sign-in is complete; website registration is still required.</p><RegistrationForm/><p className="footnote">Registration saves your site-specific ChatGPT user ID, registration date and viewer role in D1. Team permissions are assigned separately.</p><a href={chatGPTSignOutPath('/register')} target="_top">Sign out</a></>}</section></div>;
  }
  if(!titles[section])notFound();
  let data;try{data=await snapshot();}catch{return <div className="notice">Evidence storage is temporarily unavailable. Please reload to try again.</div>;}
  const {design,countries,sources,claims,metrics}=data;
  const user=await getChatGPTUser(),registered=user?await registeredAccount(user.userId):null;
  if(section==='investment') {const saved=await investmentInputs();return <><h1>Investment model</h1><InvestmentPanel initial={saved.inputs} updated={saved.updated_at} canSave={canManage(registered,true)}/></>;}
  if(section==='decision')return <><h1>{dossier.title}</h1><div className="notice">Initial planning study. Sources inform context; site offers and signed demand remain unresolved. Numerical financial results are calculated on the Investment model page.</div><p><a href="/investment">Open interactive model</a> · <a href="/deliverables/investment-memo.docx">Two-page investment memo</a> · <a href="/deliverables/system-diagram.pdf">Datacenter system diagram</a> · <a href="/architecture">Website and AI architecture</a> · <a href="https://drive.google.com/file/d/1A_Gr7akfuBEPiqKxJvKpkcRP76397HWV/view?usp=share_link" target="_blank" rel="noopener noreferrer">Demonstration video</a> · <a href="/deliverables/submission-guide.pdf">Request flow and verification guide</a></p>{dossier.sections.map(section=><section className="panel section" key={section.title}><h2>{section.title}</h2>{section.paragraphs.map((p,i)=><p key={i}>{p}</p>)}</section>)}<section className="panel section"><h2>Sources</h2>{sources.map((s:any)=><p key={s.id}><a href={s.url}>[S{s.id}] {s.publisher}: {s.title}</a> · accessed {s.accessed_at}</p>)}</section></>;
  if(section==='manage')return <><h1>Manage saved project evidence</h1>{canManage(registered)?<ManagementForms design={design} admin={canManage(registered,true)}/>:<div className="notice">Project editor access is required. Sign in, register and give your account ID to the project administrator. Public registration never grants editing permissions.</div>}</>;
  return <><div className="page-heading"><div><p className="eyebrow">Global Datacenter Design Explorer</p><h1>{titles[section]}</h1><p>{section==='country-comparison'?'Compare the evidence, its scope and its gaps before choosing a location.':section==='initial-design'?'A proposed system and its assumptions, pending site and equipment validation.':section==='evidence'?'Trace each statement to a source, assumption or unresolved question.':'Discuss the design using the current evidence and clearly labelled assumptions.'}</p></div><span className="badge">Initial concept</span></div>
  {section==='country-comparison'&&<>
    <div className="notice">Reporting periods and geographic scope differ. National power-system demand is not available capacity for a new datacenter. Unknown values are not zero.</div>
    <div className="three-column">{countries.map((c:any)=>{const carbon=metrics.find((m:any)=>m.country_id===c.id&&m.metric_name==='electricity_generation_carbon_intensity'&&m.source_id===5&&m.value!==null);const demand=metrics.find((m:any)=>m.country_id===c.id&&m.metric_name==='electricity_demand'&&m.source_id===6&&m.value!==null);return <article className={`panel country-card ${c.id===1?'primary':''}`} key={c.id}><span className="country-code">{c.id===1?'FI / Main design case':c.id===2?'CA / Comparison case':'SG / Comparison case'}</span><h2>{c.name}</h2><p className="location">{c.region}</p><dl><dt>Electricity evidence</dt><dd>{c.id===1?'95% fossil-free; 57% renewable':c.id===2?'Generation by source in MW':'94% natural gas'}<small>{c.id===1?'2024 domestic production; categories overlap [S4]':c.id===2?'Hourly provincial snapshot; not annual shares [S7]':'2024 national fuel mix [S5]'}</small></dd><dt>{c.id===2?'Latest demand snapshot':'Carbon intensity'}</dt><dd>{c.id===2?(demand?`${Number(demand.value).toLocaleString()} MW`:'Unknown'):carbon?`${carbon.value} ${carbon.unit}`:'Unknown'}<small>{countrySnapshotNote(c.id,demand,carbon)}</small></dd><dt>Site grid capacity and price</dt><dd>Unknown</dd></dl><p className="footnote">{c.id===1?'LUMI is a local cooling example [S1]. Its infrastructure does not prove capacity is available to this proposal.':c.id===2?'Data covers Québec excluding off-grid regions. Local connection, climate and cooling-water studies remain pending.':'Historical API series end in 2021 or 2013. The newer curated EMA source is displayed separately.'}</p></article>;})}</div>
    <p><a href="/decision">Read the sourced climate, permitting, energy and academic-access comparison</a></p><section className="section panel"><div className="section-heading"><h2>Sourced energy metrics</h2><span className="muted">Latest record per source and category</span></div><MetricTable metrics={metrics}/></section>
    <section className="panel"><h2>Site evidence still needed for a fair comparison</h2><div className="table-wrap"><table><thead><tr><th>Indicator</th><th>Finland / Kajaani</th><th>Canada / Québec</th><th>Singapore</th></tr></thead><tbody>{['Site electricity tariff and connection timing','Reported datacenter count and comparable capacity','Hourly climate and cooling constraints','Water availability and peak demand','Fiber availability, latency and route diversity'].map(x=><tr key={x}><td>{x}</td><td>Unknown / research pending</td><td>Unknown / research pending</td><td>Unknown / research pending</td></tr>)}</tbody></table></div></section>
  </>}
  {section==='initial-design'&&<>
    <p className="footnote">For the browser, database and AI request flow, see <a href="/architecture">Website Architecture</a>. The diagram below describes the physical datacenter.</p>
    <div className="notice">Reference engineering below uses the original 20 MW IT / 25 MW facility concept. Current saved baseline: {design.it_load_mw} MW IT, PUE {design.pue}. Resize reference equipment before approval if inputs change. All service and equipment capacities are proposed targets. The exact site, uptime target and detailed equipment configuration are not confirmed.</div>
    <section className="panel"><div className="section-heading"><h2>Power, heat and data paths</h2><Badge kind="design_decision"/></div><p className="eyebrow">Primary power</p><div className="diagram"><div className="node"><strong>Finnish grid</strong><span>25 MW request · unconfirmed</span></div><span className="flow-arrow" aria-hidden="true">→</span><div className="node"><strong>Switchgear & transformers</strong><span>Voltage and independent paths TBD</span></div><span className="flow-arrow" aria-hidden="true">→</span><div className="node"><strong>UPS & distribution</strong><span>10-minute target</span></div><span className="flow-arrow" aria-hidden="true">→</span><div className="node"><strong>IT + cooling</strong><span>20 MW IT / 25 MW facility</span></div></div><p className="diagram-caption">Standby diesel connects through transfer and distribution equipment to protected loads. N+1 generation aims to retain 25 MW usable output after the largest generator fails; switching and cooling continuity remain to be demonstrated.</p><p className="eyebrow">Heat rejection</p><div className="diagram"><div className="node"><strong>GPU cold plates</strong><span>Residual air cooling as needed</span></div><span className="flow-arrow" aria-hidden="true">→</span><div className="node"><strong>CDUs & closed loops</strong><span>Redundant pumps · leak detection</span></div><span className="flow-arrow" aria-hidden="true">→</span><div className="node"><strong>Dry coolers / refrigeration</strong><span>Weather-dependent operation</span></div><span className="flow-arrow" aria-hidden="true">→</span><div className="node"><strong>Outdoor heat rejection</strong><span>Heat recovery optional</span></div></div><p className="eyebrow">Network</p><div className="diagram"><div className="node"><strong>University connections</strong><span>Two diverse 100 Gbit/s routes assumed</span></div><span className="flow-arrow" aria-hidden="true">→</span><div className="node"><strong>Edge network</strong><span>Route independence pending</span></div><span className="flow-arrow" aria-hidden="true">→</span><div className="node"><strong>GPU fabric & storage</strong><span>Sized to selected workloads</span></div></div></section>
    <section className="section"><div className="three-column"><article className="panel"><Badge kind="unknown"/><h3>Largest electrical failure</h3><p>Assess both supply routes and downstream distribution. Two cables may share a substation. Transformer ratings, protection and surviving capacity remain unknown.</p></article><article className="panel"><Badge kind="assumption"/><h3>48-hour grid outage</h3><p>UPS bridges the transfer to diesel generation. At 25 MW, 48 hours needs 1,200 MWh delivered; fuel volume and reliability are unverified.</p></article><article className="panel"><Badge kind="unknown"/><h3>Cooling and water</h3><p>Avoid routine cooling towers. Annual use, peak supply, filling, makeup and fire-water requirements remain unknown. Verify summer performance and winter freeze protection.</p></article></div></section>
    <section className="panel"><h2>Saved design assumptions and decisions</h2><p className="footnote">Last design update: {design.updated_at}. Proposal classification remains visible for each statement.</p>{claims.filter((c:any)=>c.claim_type!=='evidence').map((c:any)=><article className="claim" key={c.id}><Badge kind={c.claim_type}/><p>{c.claim_text}</p><small>{c.status} · Updated {c.updated_at}</small></article>)}</section>
    <section className="section panel"><h2>Investment stress cases and detailed engineering</h2><p><a href="/investment">Compare all three options, stress cases and annual cash flows</a></p><p><a href="/decision">Read quantified reference failure analysis, demand, financing and governance</a></p><p><a href="/deliverables/system-diagram.pdf">Download the one-page system diagram</a></p></section>
  </>}
  {section==='evidence'&&<>
    <p><a href="/architecture">See how evidence moves through the website and AI adviser</a></p>
    <EvidenceFilter claims={claims} sources={sources} canRefresh={canManage(registered)}/>
    <details className="panel"><summary>Latest metric records and provenance</summary><MetricTable metrics={metrics}/></details>
  </>}
  {section==='ask-the-adviser'&&<section className="panel adviser-intro"><div className="section-heading"><h2>Datacenter Design Adviser</h2><span className="badge">{adviserConfigured()?'AI connected':'Temporarily unavailable'}</span></div><p>The adviser evaluates this initial design using stored evidence, calculations and source citations. It distinguishes proposals from verified information.</p><div className="notice">Answers use the current D1 design and controlled evidence tools. Supporting sources, assumptions and uncertainties are shown with each answer.</div>{!user?<><h3>Sign in with ChatGPT</h3><p>The design and evidence are public. Sign in, then complete website registration to access the adviser.</p><a className="button" href={chatGPTSignInPath('/register')} target="_top">Sign in with ChatGPT</a></>:!registered?<><h3>Complete website registration</h3><p>Signed in as {user.displayName}. Register this identity with the website before asking questions.</p><RegistrationForm/></>:<><p className="muted">Signed in as {user.displayName} · {registered.role}</p><AdviserForm/></>}<p className="footnote">The adviser concerns an initial design concept and cannot issue engineering certification. Missing or conflicting evidence must be identified explicitly.</p></section>}
  </>;
}
