// Generated by ../sync_schema.py from ../d1-schema.sql. Edit the canonical SQL.
import { sqliteTable, integer, real, text, check, index } from 'drizzle-orm/sqlite-core';
import { sql } from 'drizzle-orm';
export const users = sqliteTable('users', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  authenticated_user_id: text('authenticated_user_id').notNull().unique(),
  email: text('email').unique(),
  display_name: text('display_name'),
  password_hash: text('password_hash'),
  team_id: integer('team_id'),
  role: text('role').notNull().default(sql.raw("'viewer'")),
  registered_at: text('registered_at').notNull(),
}, (t) => [
  check('users_check_1', sql.raw("role IN ('viewer', 'editor', 'team_admin')")),
  check('users_check_2', sql.raw('password_hash IS NULL OR email IS NOT NULL')),
]);
export const sessions = sqliteTable('sessions', {
  session_hash: text('session_hash').primaryKey().notNull().unique(),
  user_id: integer('user_id').notNull().references(() => users.id),
  expires_at: integer('expires_at').notNull(),
  created_at: text('created_at').notNull(),
}, (t) => [
  index('idx_sessions_expiry').on(t.expires_at),
]);
export const auth_limits = sqliteTable('auth_limits', {
  bucket_key: text('bucket_key').primaryKey().notNull().unique(),
  attempts: integer('attempts').notNull(),
  expires_at: integer('expires_at').notNull(),
}, (t) => [
  check('auth_limits_check_1', sql.raw('attempts > 0')),
  index('idx_auth_limits_expiry').on(t.expires_at),
]);
export const countries = sqliteTable('countries', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  name: text('name').notNull().unique(),
  region: text('region'),
}, (t) => [
]);
export const sources = sqliteTable('sources', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  publisher: text('publisher').notNull(),
  title: text('title').notNull(),
  url: text('url').notNull(),
  source_type: text('source_type').notNull(),
  publication_date: text('publication_date'),
  accessed_at: text('accessed_at').notNull(),
  documentation_url: text('documentation_url'),
  dataset_id: text('dataset_id'),
  endpoint_url: text('endpoint_url'),
  auth_type: text('auth_type').notNull().default(sql.raw("'unknown'")),
  auth_header: text('auth_header'),
  license: text('license'),
  verification_status: text('verification_status').notNull().default(sql.raw("'unverified'")),
  verified_at: text('verified_at'),
  last_refresh_at: text('last_refresh_at'),
  last_refresh_status: text('last_refresh_status').notNull().default(sql.raw("'never'")),
  last_refresh_error: text('last_refresh_error'),
  notes: text('notes'),
}, (t) => [
  check('sources_check_1', sql.raw("source_type IN ('webpage', 'report', 'dataset', 'api')")),
  check('sources_check_2', sql.raw("auth_type IN ('none', 'api_key', 'unknown')")),
  check('sources_check_3', sql.raw("verification_status IN ('unverified', 'documented', 'tested', 'needs_key')")),
  check('sources_check_4', sql.raw("last_refresh_status IN ('never', 'succeeded', 'failed')")),
  check('sources_check_5', sql.raw("auth_type <> 'api_key' OR (auth_header IS NOT NULL AND length(trim(auth_header)) > 0)")),
  check('sources_check_6', sql.raw("verification_status <> 'tested' OR (endpoint_url IS NOT NULL AND verified_at IS NOT NULL)")),
  check('sources_check_7', sql.raw("last_refresh_status = 'never' OR last_refresh_at IS NOT NULL")),
]);
export const metrics = sqliteTable('metrics', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  country_id: integer('country_id').notNull().references(() => countries.id),
  metric_name: text('metric_name').notNull(),
  category: text('category').notNull().default(sql.raw("''")),
  value: real('value'),
  value_kind: text('value_kind').notNull(),
  unit: text('unit').notNull(),
  geographic_scope: text('geographic_scope').notNull(),
  reporting_period: text('reporting_period'),
  source_timestamp: text('source_timestamp'),
  source_timezone: text('source_timezone'),
  source_record_id: text('source_record_id'),
  source_id: integer('source_id').notNull().references(() => sources.id),
  retrieved_at: text('retrieved_at').notNull(),
  confidence: text('confidence').notNull(),
  notes: text('notes').notNull(),
}, (t) => [
  check('metrics_check_1', sql.raw("value IS NULL OR typeof(value) IN ('integer', 'real')")),
  check('metrics_check_2', sql.raw("value_kind IN ('reported', 'estimate', 'forecast', 'calculated')")),
  check('metrics_check_3', sql.raw("confidence IN ('high', 'medium', 'low', 'unassessed')")),
  check('metrics_check_4', sql.raw('length(trim(notes)) > 0')),
  index('idx_metrics_country_metric').on(t.country_id, t.metric_name),
]);
export const designs = sqliteTable('designs', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  team_id: integer('team_id').notNull(),
  selected_country_id: integer('selected_country_id').references(() => countries.id),
  it_load_mw: real('it_load_mw').notNull(),
  pue: real('pue').notNull(),
  annual_operating_hours: real('annual_operating_hours').notNull(),
  cooling_strategy: text('cooling_strategy'),
  backup_strategy: text('backup_strategy'),
  design_summary: text('design_summary'),
  updated_at: text('updated_at').notNull(),
}, (t) => [
  check('designs_check_1', sql.raw("typeof(it_load_mw) IN ('integer', 'real') AND it_load_mw > 0")),
  check('designs_check_2', sql.raw("typeof(pue) IN ('integer', 'real') AND pue >= 1")),
  check('designs_check_3', sql.raw("typeof(annual_operating_hours) IN ('integer', 'real')\n            AND annual_operating_hours > 0 AND annual_operating_hours <= 8784")),
]);
export const design_claims = sqliteTable('design_claims', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  design_id: integer('design_id').notNull().references(() => designs.id),
  claim_text: text('claim_text').notNull(),
  claim_type: text('claim_type').notNull(),
  source_id: integer('source_id').references(() => sources.id),
  status: text('status').notNull(),
  notes: text('notes'),
  updated_at: text('updated_at').notNull(),
}, (t) => [
  check('design_claims_check_1', sql.raw("claim_type IN (\n            'evidence', 'assumption', 'calculation', 'design_decision', 'unknown'\n        )")),
  check('design_claims_check_2', sql.raw("status IN ('draft', 'verified', 'proposed', 'calculated', 'unresolved')")),
  check('design_claims_check_3', sql.raw("claim_type <> 'evidence' OR source_id IS NOT NULL")),
  check('design_claims_check_4', sql.raw("status <> 'verified' OR claim_type = 'evidence'")),
  index('idx_claims_design').on(t.design_id),
]);
export const adviser_requests = sqliteTable('adviser_requests', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  user_id: integer('user_id').notNull().references(() => users.id),
  created_at: integer('created_at').notNull(),
  completed_at: integer('completed_at'),
  status: text('status').notNull().default(sql.raw("'pending'")),
  model: text('model').notNull(),
  input_tokens: integer('input_tokens').notNull().default(sql.raw('0')),
  output_tokens: integer('output_tokens').notNull().default(sql.raw('0')),
  tool_calls: integer('tool_calls').notNull().default(sql.raw('0')),
  error_code: text('error_code'),
}, (t) => [
  check('adviser_requests_check_1', sql.raw("status IN ('pending','succeeded','failed')")),
  check('adviser_requests_check_2', sql.raw('input_tokens >= 0')),
  check('adviser_requests_check_3', sql.raw('output_tokens >= 0')),
  check('adviser_requests_check_4', sql.raw('tool_calls >= 0')),
  index('idx_adviser_time').on(t.created_at),
  index('idx_adviser_user_time').on(t.user_id, t.created_at),
]);
