'use client';
import { useState } from 'react';
import { ASSUMPTIONS, compare, model } from '../lib/investment.mjs';
const euro=(v:number)=>new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(v);
export function InvestmentPanel({initial,canSave,updated}:{initial:any;canSave:boolean;updated:string|null}) {
 const [inputs,setInputs]=useState(initial),[option,setOption]=useState('hybrid'),[scenario,setScenario]=useState('base'),[message,setMessage]=useState('');
 let results:any[]=[],chosen:any=null,error='';try{results=compare(inputs);chosen=model(inputs,option,scenario);}catch(e:any){error=e.message;}
 const best=results.filter(r=>r.scenario==='base').sort((a,b)=>a.npvCost-b.npvCost)[0];
 return <>
 <div className="notice">Planning estimates, not quotes or contracted demand. Same GPU-equivalent demand is served in every option, including leased bridging before opening. Saved values updated: {updated||'initial defaults'}. Experiments below do not save automatically.</div>
 {best&&<section className="panel"><h2>Lowest modeled base-case cost: {best.option}</h2><p>{euro(best.npvCost)} discounted resource cost; €{best.costPerGPUHour.toFixed(2)} per productive GPU-equivalent hour. This ranking does not establish procurement availability or justify construction without signed demand and a utility offer.</p><p>Annual assumed demand: {(best.demand/1e6).toFixed(2)} million productive hours. Full-build fleet: {best.fullGPU.toLocaleString()} GPU equivalents. Hybrid phase: {model(inputs,'hybrid').itMW.toFixed(2)} MW IT.</p></section>}
 <details className="panel section"><summary>Inspect and change every financial assumption</summary><p>Rates are constant 2026 EUR. Source references explain context; unquoted allowances are identified explicitly. IT load, PUE and hours inherit the saved design; administrators change them on Manage evidence.</p><div className="assumption-grid">{ASSUMPTIONS.map(([key,label,,min,max,note]:any)=><label key={key}>{label}<input type="number" step="any" min={min} max={max} disabled={['itMW','pue','hours'].includes(key)} value={inputs[key]} onChange={e=>setInputs({...inputs,[key]:Number(e.target.value)})}/><small>{note}</small></label>)}</div><div className="account-actions"><button onClick={()=>setInputs(initial)}>Reset experiment</button>{canSave&&<button disabled={!!error} onClick={async()=>{try{const r=await fetch('/api/save-finance',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({inputs})});const d:any=await r.json();if(!r.ok)throw Error(d.error);setMessage('Financial assumptions saved. Reload to confirm the saved snapshot.');}catch(e:any){setMessage(e.message);}}}>Save financial assumptions</button>}</div><p role="status">{message||error}</p></details>
 {results.length>0&&<section className="section panel"><h2>Required scenarios and options</h2><div className="table-wrap"><table><caption>2026 EUR estimates. Opex is the first owned-operation year, or year 1 for lease.</caption><thead><tr><th>Scenario / option</th><th>Opening year</th><th>Cash before opening</th><th>Annual opex</th><th>Discounted €/productive hour</th><th>Capital at risk</th><th>10-year cost NPV</th></tr></thead><tbody>{results.map(r=><tr key={r.option+r.scenario}><td>{r.scenario} / {r.option}</td><td>{r.opening}</td><td>{euro(r.preOpeningCash)}</td><td>{euro(r.annualOperatingCost)}</td><td>€{r.costPerGPUHour.toFixed(2)}</td><td>{euro(r.capitalAtRisk)}</td><td>{euro(r.npvCost)}</td></tr>)}</tbody></table></div><p className="footnote">Delay: owned opening slips one year, completed works incur holding cost and more bridge leasing; GPUs are bought only in the year before actual opening. Half utilization: demand halves; idle power and fixed costs remain. Lease has no project-grid exposure. Before-opening cash includes capital, bridge opex and interest before the opening year; member equity cash is shown below. Capital at risk is net unrecoverable initial capex plus pre-opening opex/interest and a three-month cloud cancellation exposure. It is a downside exposure measure, not another cost to add to NPV.</p></section>}
 <section className="panel"><h2>Ten-year annual cash flows</h2><div className="input-row"><label>Option<select value={option} onChange={e=>setOption(e.target.value)}>{['build','lease','hybrid'].map(x=><option key={x}>{x}</option>)}</select></label><label>Scenario<select value={scenario} onChange={e=>setScenario(e.target.value)}>{['base','delay','half'].map(x=><option key={x}>{x}</option>)}</select></label></div>
 {chosen&&<><div className="table-wrap"><table><thead><tr>{['Year','Facility','Grid','GPU / replacement','Lease','Electricity','Staff','Maintenance','Holding','Admin','Interest','Debt drawn','Principal','Member cash'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{chosen.rows.map((r:any)=><tr key={r.year}><td>{r.year}</td>{['facilityCapex','gridCapex','gpuCapex','lease','electricity','staff','maintenance','holding','admin','interest','draw','principal','memberCash'].map(k=><td key={k}>{euro(r[k])}</td>)}</tr>)}</tbody></table></div><p>Total resource cost: {euro(chosen.totalCost)}. Financing interest: {euro(chosen.totalInterest)}. Member cash paid: {euro(chosen.totalMemberCash)}. Outstanding debt at year 10: {euro(chosen.terminalDebt)} (additional obligation). Member cash before opening: {euro(chosen.preOpeningMemberCash)}.</p><p>Annual allocated unused-capacity burden in first operating year: {euro(chosen.unusedCapacityCost)}. This allocates fixed staffing, maintenance and straight-line capital consumption to idle capacity; it is already represented in the model and is not an extra charge.</p><details><summary>Energy and delivered hours</summary><div className="table-wrap"><table><thead><tr><th>Year</th><th>Owned productive GPU-hours</th><th>Leased productive GPU-hours</th><th>Owned-site GWh</th><th>Unused available GPU-hours</th></tr></thead><tbody>{chosen.rows.map((r:any)=><tr key={r.year}><td>{r.year}</td>{['ownedHours','leasedHours','energyGWh','unusedGPUHours'].map(k=><td key={k}>{r[k].toLocaleString('en-US',{maximumFractionDigits:2})}</td>)}</tr>)}</tbody></table></div></details></>}
 <p className="footnote">No income or profit forecast: member funding covers costs. NPV discounts capital and operating resource costs, excluding debt draws, principal and interest to avoid double-counting finance. Separate member cash includes debt financing; year-10 debt must still be settled. No terminal resale, tax deductions, grants, heat revenue or future GPU performance gains are credited: explicit conservative modeling choices, not unknown measured zeros. VAT is assumed recoverable; nonrecoverable tax treatment needs institutional review. Availability and performance equivalence of cloud and owned clusters must be benchmarked before signing.</p></section>
 {results.length>0&&<section className="section panel"><h2>Demand sensitivity</h2><div className="table-wrap"><table><thead><tr><th>Full-fleet productive utilization</th><th>Build €/hour</th><th>Lease €/hour</th><th>Hybrid €/hour</th><th>Lowest modeled cost</th></tr></thead><tbody>{[.125,.25,.4,.6,.8].map(u=>{const r=['build','lease','hybrid'].map(o=>model({...inputs,utilization:u},o));return <tr key={u}><td>{u*100}%</td>{r.map(x=><td key={x.option}>€{x.costPerGPUHour.toFixed(2)}</td>)}<td>{r.sort((a,b)=>a.npvCost-b.npvCost)[0].option}</td></tr>;})}</tbody></table></div><p>Also test lease USD 5.54 (published cluster rate [S14]), facility costs ±30%, electricity €0.05–0.20/kWh, and GPU replacement every 3–5 years using the controls above.</p></section>}
 <p><a href="/decision">Read decision gates, source links, limitations and deliverables</a></p>
 </>;
}
