'use client';
import { useState } from 'react';
import { Refresh } from './widgets';
export function EvidenceFilter({claims,sources,canRefresh}:{claims:any[];sources:any[];canRefresh:boolean}) {
 const [search,setSearch]=useState(''),[kind,setKind]=useState('all');const match=(x:any)=>JSON.stringify(x).toLowerCase().includes(search.toLowerCase());
 const selected=claims.filter(c=>(kind==='all'||c.claim_type===kind)&&match(c));
 return <><section className="panel"><h2>Filter evidence</h2><div className="input-row"><label>Search claims and sources<input value={search} onChange={e=>setSearch(e.target.value)}/></label><label>Classification<select value={kind} onChange={e=>setKind(e.target.value)}>{['all','evidence','assumption','calculation','design_decision','unknown'].map(k=><option key={k}>{k}</option>)}</select></label></div><p role="status">{selected.length} matching claims</p>{selected.map(c=><article className="claim" key={c.id}><span className={`badge ${c.claim_type}`}>{c.claim_type}</span><p>{c.claim_text}</p><small>{c.status} · {c.updated_at} {c.source_id&&<a href={`#source-${c.source_id}`}>[S{c.source_id}]</a>}</small></article>)}</section><section className="panel section"><h2>Sources and refresh status</h2>{sources.filter(s=>match(s)||selected.some(c=>c.source_id===s.id)).map(s=><article className="source" id={`source-${s.id}`} key={s.id}><h3><a href={s.url} target="_blank" rel="noreferrer">[S{s.id}] {s.title}</a></h3><p>{s.publisher} · {s.verification_status}</p><p>{s.notes}</p><small>Publication: {s.publication_date||'not stated'} · Accessed: {s.accessed_at} · Refresh: {s.last_refresh_status} {s.last_refresh_at||''}</small>{s.last_refresh_error&&<p role="status">{s.last_refresh_error}</p>}{canRefresh&&[6,7,8,11].includes(s.id)&&<Refresh source={s.id}/>}</article>)}</section></>;
}
export function ManagementForms({design,admin}:{design:any;admin:boolean}) {
 const [message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function submit(e:React.FormEvent<HTMLFormElement>,action:string) {
  e.preventDefault();const form=new FormData(e.currentTarget);const body:any=Object.fromEntries(form.entries());
  for(const k of ['it_load_mw','pue','annual_operating_hours','user_id'])if(k in body)body[k]=Number(body[k]);
  setBusy(true);setMessage('');try {const r=await fetch(`/api/${action}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d:any=await r.json();if(!r.ok)throw Error(d.error);setMessage('Saved. Reload the design or evidence page to inspect the new records.');}catch(e:any){setMessage(e.message);}finally{setBusy(false);}
 }
 return <><p role="status">{message}</p>{admin&&<section className="panel"><h2>Update saved design</h2><form onSubmit={e=>submit(e,'save-design')}><div className="input-row">{[['it_load_mw','IT MW'],['pue','PUE'],['annual_operating_hours','Annual hours']].map(([key,label])=><label key={key}>{label}<input name={key} type="number" step="any" required defaultValue={design[key]}/></label>)}</div><label>Reason and evidence for the change<textarea name="reason" maxLength={1000} required/></label><p>Updates baseline calculations atomically. Detailed engineering remains a reference concept and must be resized before approval.</p><button disabled={busy}>Save design</button></form></section>}
 <section className="panel section"><h2>Add a reviewed source and claim</h2><p>This stores a citation and your review. It does not fetch the URL or create an arbitrary API integration. Never enter credentials or personal information.</p><form onSubmit={e=>submit(e,'add-evidence')}><div className="assumption-grid">{[['publisher','Publisher'],['title','Source title'],['url','HTTPS source URL']].map(([key,label])=><label key={key}>{label}<input name={key} type={key==='url'?'url':'text'} required maxLength={key==='url'?2000:200}/></label>)}<label>Classification<select name="claim_type">{['evidence','assumption','design_decision','unknown'].map(k=><option key={k}>{k}</option>)}</select></label></div><label>Claim<textarea name="claim" required maxLength={4000}/></label><label>Verification notes, reporting period and limitations<textarea name="notes" required maxLength={4000}/></label><button disabled={busy}>Save evidence</button></form></section>
 {admin&&<section className="panel section"><h2>Assign project permissions</h2><p>The person must register first and provide their numeric account ID. Self-role changes and changes to another team's members are rejected.</p><form onSubmit={e=>submit(e,'assign-role')}><label>Registered account ID<input name="user_id" type="number" min="1" required/></label><label>Role<select name="role">{['viewer','editor','team_admin'].map(k=><option key={k}>{k}</option>)}</select></label><button disabled={busy}>Assign role</button></form></section>}</>;
}
